### ISSUE TITLE
1.0.17 ou 1.0.18 ?

### ISSUE THREAD

**Issue by ltaulell** [l-modolo/UrQt#1]
Salut,

Toute petite incohérence :

J'ai compilé UrQt, téléchargé au LBBE, au PSMN. L'archive annonce une version 1.0.17 (comme la page web https://lbbe.univ-lyon1.fr/Download-5172.html?lang=fr), mais une fois compilé, le binaire annonce une version 1.0.18.

Une mise à jour de l'archive et/ou une release officielle 1.0.18 sur github ?

**Comment by l-modolo** [comment]
I changed the version to 1.0.18 in the --version message. The github repository is now the reference of the UrQt code
