### ISSUE TITLE
malloc error

### ISSUE THREAD

**Issue by cbompard** [l-modolo/UrQt#5]
Hello,
I'm working on the LBBE's cluster and I've been trying to use this command : 
```
programs/UrQt/UrQt --in datas/dmel_sra/embryo_0-2h_R1.fastq.gz --inpair datas/dmel_sra/embryo_0-2h_R2.fastq.gz --out datas/dmel_sra/embryo_0-2h_R1_trimmed.fastq.gz --outpair datas/dmel_sra/embryo_0-2h_R2_trimmed.fastq.gz --t 20 --gz --min_read_size 40
```

But for some files I get this error : 
```
UrQt: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Abandon
```

For one of the files it worked before but not anymore.
It doesn't seem to depend on the size of the file and I tried allocating more memory, but it doesn't solve the problem.

**Comment by l-modolo** [comment]
Hello @cbompard,

you can try to compile from the commit d62c1f8

```sh
git clone https://github.com/l-modolo/UrQt
cd UrQt
git checkout d62c1f8
make
```

however, there may be faster alternative to UrQt nowadays, like [fastp](https://github.com/OpenGene/fastp).

Best
